/**
 * Lightning Network payment payload for the Exact scheme.
 *
 * Contains the payment preimage which serves as proof of payment
 * after a Lightning invoice has been successfully paid.
 */
export type ExactLightningPayload = {
  /**
   * Hex-encoded payment preimage (32 bytes = 64 hex characters).
   * This is the secret revealed when a Lightning payment is settled,
   * and serves as cryptographic proof that payment was made.
   */
  preimage: string;
};

/**
 * Extra fields included in Lightning payment requirements.
 *
 * The facilitator generates a BOLT11 invoice and includes it here so
 * the client knows exactly which invoice to pay via NWC.
 */
export type LightningPaymentRequirementsExtra = {
  /**
   * BOLT11-encoded Lightning invoice generated by the facilitator.
   * The client must pay this invoice to fulfil the payment requirement.
   */
  invoice: string;
};

/**
 * Minimal interface for a Lightning client capable of paying BOLT11 invoices.
 * Any object implementing this method is accepted (e.g. NWCClient).
 */
export interface Wallet {
  payInvoice(args: { invoice: string }): Promise<{ preimage: string }>;
}
